# Base configs
baseurl: "https://biws.co.uk"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Art by Biws"
subtitle: "Original painting, drawing & sculpture"
author: "Billie Burvill"
header:
 title: "Art by Biws"
 subtitle: "by Billie Burvill"
footer:
 name: "Hey there, my name is Billie"
 bio: "Personalised Pet and People portraits with paint, pencil and sculpture."

social_urls:
  facebook: "https://www.facebook.com/billieburvillfineartandreiki"
  twitter: "https://www.twitter.com/biws"
  instagram: "https://www.instagram.com/art.by.bille"
  linkedin: "https://in.linkedin.com/in/billieburvill"
 
